CREATE DATABASE CafeManagement
GO

USE CafeManagement
GO

CREATE TABLE Account
(
	FullName NVARCHAR(100) NOT NULL DEFAULT N'Staff',
	UserName NVARCHAR(100) PRIMARY KEY,
	DateofBirth NVARCHAR(100) NOT NULL,
	PassWord NVARCHAR(100) NOT NULL DEFAULT 0,
	Type INT NOT NULL DEFAULT 0,
	Image NVARCHAR(300) NULL,
)
GO

CREATE TABLE Beverage
(
	id INT IDENTITY PRIMARY KEY,
	name NVARCHAR(100) NOT NULL DEFAULT N'NotNamed',
	idMenu INT NOT NULL,
	price INT NOT NULL DEFAULT 0,
	image NVARCHAR(300) NULL,

	FOREIGN KEY (idMenu) REFERENCES dbo.Menu(id)
)
GO

CREATE TABLE CoffeeTable
(
	id INT IDENTITY PRIMARY KEY,
	name NVARCHAR(100) NOT NULL DEFAULT N'NotNamed',
	status NVARCHAR(100) NOT NULL DEFAULT N'Empty'  
)
GO

CREATE TABLE Menu
(
	id INT IDENTITY PRIMARY KEY,
	name NVARCHAR(100) NOT NULL DEFAULT N'NotNamed'
)
GO

CREATE TABLE Bill
(
	id INT IDENTITY PRIMARY KEY,
	DateCheckin DATE NOT NULL DEFAULT GETDATE(),
	DateCheckout DATETIME,
	staff NVARCHAR(100) NOT NULL DEFAULT N'Notnamed',
	idTable INT NOT NULL,
	status INT NOT NULL DEFAULT 0,
	idMember INT NULL DEFAULT 0,
	nameMember NVARCHAR(100) NOT NULL DEFAULT N'Notnamed',
	discount INT,
	totalPrice FLOAT,
	point FLOAT NOT NULL DEFAULT 0,

	FOREIGN KEY (idTable) REFERENCES dbo.CoffeeTable(id)
)
GO

CREATE TABLE BillInfor
(
	id INT IDENTITY PRIMARY KEY,
	idBill INT NOT NULL,
	idBeverage	INT NOT NULL,
	quantity INT NOT NULL DEFAULT 0,

	FOREIGN KEY (idBill) REFERENCES dbo.Bill(id),
	FOREIGN KEY (idBeverage) REFERENCES dbo.Beverage(id)
)
GO

CREATE TABLE Ingredient
(
	id INT IDENTITY PRIMARY KEY,
	name NVARCHAR(100) NOT NULL,
	supplier NVARCHAR(100) NOT NULL,
	quantity INT NOT NULL,
	usedquantity INT NOT NULL,
	leftquantity INT NOT NULL,
	dateIn NVARCHAR(100) NOT NULL,
	dateOut NVARCHAR(100) NOT NULL,
)
GO

CREATE TABLE Membership
(
	id INT IDENTITY PRIMARY KEY,
	name NVARCHAR(100) NOT NULL,
	dateofbirth NVARCHAR(100) NOT NULL,
	phonenumber NVARCHAR(100) NOT NULL,
	totalpoint FLOAT NOT NULL DEFAULT 0,
)
GO